### ISSUE TITLE
Corregir plantilla de comandos 

### ISSUE THREAD

**Issue by EnzoDiazDev** [newlands-quest/game#10]
El nombre de la plantilla de comandos se llama "Feature Request", cuando debería ser "Command Request"
Archivo (linea 1): https://github.com/newlands-quest/game/blob/main/.github/ISSUE_TEMPLATE/command_request.yml 

Además, sería ideal añadir un campo para rellenar con el *trigger* del comando 
Ejemplo: 
```yaml
- type: textarea
  validations:
    required: true
  attributes:
    label: "What is the trigger of the command?"
    description: "Specify how you would use the command"
    placeholder: "!do somethig @john"
```
